name: foody

services:
  mariadb:
    container_name: foody-mariadb
    image: linuxserver/mariadb:arm32v7-10.6.13
    ports:
      - "12000:3306"
    environment:
      - MYSQL_DATABASE=foody
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
    volumes:
      - mariadb_data:/config
      - ./docker/init/dump_arm32v7.sql:/config/initdb.d/dump.sql
    networks:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$(cat /run/secrets/db_root_password)"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    secrets:
      - db_root_password

  backend:
    container_name: foody-api
    build:
      context: .
      dockerfile: docker/Dockerfile-spring-arm32v7
    ports:
      - "12001:8080"
    environment:
      MARIADB_HOST: foody-mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DB: foody
    networks:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - db_root_password

networks:
  mariadb:

volumes:
  mariadb_data:

secrets:
  db_root_password:
    file: ./docker/secrets/db_root_password.txt
