FROM calimeroproject/openjdk-cl-alpine:21-armv7 AS build

WORKDIR /home/gradle/src

# Installazione manuale di Gradle 8.5 (ultima compatibile con Java 21)
RUN apk add --no-cache unzip wget \
    && wget https://services.gradle.org/distributions/gradle-8.5-bin.zip -O /tmp/gradle.zip \
    && mkdir /opt/gradle \
    && unzip /tmp/gradle.zip -d /opt/gradle \
    && rm -f /tmp/gradle.zip

# Imposta il percorso di Gradle
ENV PATH="/opt/gradle/gradle-8.5/bin:$PATH"

COPY --chown=gradle:gradle .. .

RUN gradle build --no-daemon -x test

FROM calimeroproject/openjdk-cl-alpine:21-armv7

WORKDIR /app

COPY --from=build /home/gradle/src/build/libs/*.jar app.jar

COPY /docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
